#!/bin/sh
# Exact-location regression for schema-3 pools.  This deliberately exercises
# the human-facing Ante/blind/source coordinates separately from the legacy
# Legendary RNG-Ante coordinate system.
set -eu

SNAPSHOT="${1:-native_search.cfg}"
COUNT="${2:-1000000}"
TAG="${TAG:-tag_charm}"
LEGENDARY="${LEGENDARY:-j_perkeo}"
LUAJIT_BIN="${LUAJIT:-luajit}"
OUT="${TMPDIR:-/tmp}/brainstorm_pool_exact_location_regression"
rm -rf "$OUT"
mkdir -p "$OUT"

case "$(uname -s)" in
	MINGW*|MSYS*|CYGWIN*) EXE=.exe; BUILD=native/build_windows.sh
		native_path() { cygpath -m "$1"; } ;;
	*) EXE=; BUILD=native/build.sh
		native_path() { printf '%s\n' "$1"; } ;;
esac

sh "$BUILD"
"$LUAJIT_BIN" tests/align_snapshot_prng.lua "$SNAPSHOT" > "$OUT/snapshot.cfg"
grep -q "^tagdef $TAG 1 " "$OUT/snapshot.cfg" || {
	echo "FAIL: exact-location fixture tag $TAG is unavailable"; exit 1;
}
grep -q "^jokerdef 4 $LEGENDARY 1$" "$OUT/snapshot.cfg" || {
	echo "FAIL: exact-location fixture Legendary $LEGENDARY is unavailable"; exit 1;
}

write_criteria() {
	file="$1"
	shift
	{
		echo "poolver 1"
		echo "threads 4"
		echo "start 0"
		echo "count $COUNT"
		echo "checkpoint $COUNT"
		echo "chunk 16384"
		echo "resume 0"
		echo "format binary"
		echo "tag_route collect"
		for line in "$@"; do echo "$line"; done
		echo "end"
	} > "$file"
}

# Phase boundaries for tags: the two single-position rules must write their
# exact human location into both the self-describing header and every member's
# event metadata.
write_criteria "$OUT/tag-small.cfg" "tag $TAG 1 small 1 small 1"
write_criteria "$OUT/tag-big.cfg" "tag $TAG 1 big 1 big 1"

# A collected Charm at A1 Small replaces that shop pair with the immediate
# Charm reward.  A Soul found there must be source=Charm, never source=Shop.
write_criteria "$OUT/charm.cfg" \
	"tag $TAG 1 small 1 small 1" \
	"legendary $LEGENDARY 1 small 1 small 0 charm"
write_criteria "$OUT/charm-wrong-source.cfg" \
	"tag $TAG 1 small 1 small 1" \
	"legendary $LEGENDARY 1 small 1 small 0 shop"

# Human A1 Boss is generated by the Ante-2 RNG stream.  That mapping is a
# compact discriminator between new human locations and old MIN/MAX syntax.
write_criteria "$OUT/boss.cfg" \
	"legendary $LEGENDARY 1 boss 1 boss 0 shop"
write_criteria "$OUT/legacy-a1.cfg" "legendary $LEGENDARY 1 1 0"
write_criteria "$OUT/legacy-a2.cfg" "legendary $LEGENDARY 2 2 0"

for name in tag-small tag-big charm boss; do
	"./native/brainstorm_seed_pool$EXE" scan "$OUT/snapshot.cfg" \
		"$OUT/$name.cfg" "$OUT/$name.bspool"
	"./native/brainstorm_seed_pool$EXE" export "$OUT/$name.bspool" \
		"$OUT/$name.txt"
	[ -s "$OUT/$name.txt" ] || {
		echo "FAIL: $name sample is empty; raise COUNT (currently $COUNT)"; exit 1;
	}
done

# The targeted Charm/Omen branches intentionally let one seed expose its first
# Soul at different locations on different valid routes.  Legacy coordinate
# compatibility is a single-route property, so give that portion of the test a
# snapshot with only those two alternate-route sources disabled.  The primary
# fixtures above still exercise both features with the real snapshot.
awk '
	$1 == "tagdef" && $2 == "tag_charm" { $3 = 0 }
	$1 == "vouchdef" && $2 == "v_omen_globe" { $3 = 0 }
	$1 == "vouchroute" && $2 == "v_omen_globe" { $3 = 0 }
	$1 == "vouchowned" && $2 == "v_omen_globe" { next }
	{ print }
' "$OUT/snapshot.cfg" > "$OUT/legacy-snapshot.cfg"
"./native/brainstorm_seed_pool$EXE" scan "$OUT/legacy-snapshot.cfg" \
	"$OUT/boss.cfg" "$OUT/legacy-boss.bspool"
"./native/brainstorm_seed_pool$EXE" export "$OUT/legacy-boss.bspool" \
	"$OUT/legacy-boss.txt"
[ -s "$OUT/legacy-boss.txt" ] || {
	echo "FAIL: alternate-free legacy Boss sample is empty; raise COUNT (currently $COUNT)"; exit 1;
}

grep -a -q "^tag $TAG 1 small 1 small 1$" "$OUT/tag-small.bspool"
grep -a -q "^tag $TAG 1 big 1 big 1$" "$OUT/tag-big.bspool"
grep -a -q "^legendary $LEGENDARY 1 small 1 small 0 charm$" \
	"$OUT/charm.bspool"
grep -a -q "^legendary $LEGENDARY 1 boss 1 boss 0 shop$" \
	"$OUT/boss.bspool"

# Decode the schema-3 inverted metadata table and require the selected event
# on every local record. Descriptor layout is kind,key,Ante,phase,source,
# Soul ordinal,flags; phases are Boss=0, Small=1, Big=2 and sources are
# none=0, Shop=1, Charm=2, Ethereal=3.
check_metadata() {
	python3 - "$1" "$2" "$3" "$4" "$5" "$6" <<'PY'
import re
import struct
import sys

path, want_kind, want_key, want_ante, want_phase, want_source = sys.argv[1:]
want = (int(want_kind), want_key, int(want_ante), int(want_phase),
        int(want_source))
raw = open(path, "rb").read()
prefix = raw[:8192].split(b"\0", 1)[0].decode("ascii")

def field(name):
    match = re.search(r"^%s (\S+)$" % re.escape(name), prefix, re.M)
    assert match, "%s: missing %s" % (path, name)
    return match.group(1)

assert re.search(r"^BRAINSTORM_SEED_POOL 3$", prefix, re.M), path
header_bytes = int(field("header_bytes"))
data_bytes = int(field("data_bytes"))
records = int(field("records"))
assert records > 0

def varint(payload, pos):
    value = 0
    shift = 0
    start = pos
    while True:
        assert pos < len(payload), "%s: truncated metadata varint" % path
        byte = payload[pos]
        pos += 1
        value |= (byte & 0x7f) << shift
        if not byte & 0x80:
            if pos - start > 1:
                assert value >= 1 << (7 * (pos - start - 1)), \
                    "%s: non-canonical metadata varint" % path
            return value, pos
        shift += 7
        assert shift < 70, "%s: oversized metadata varint" % path

pos = header_bytes
end = header_bytes + data_bytes
seen_records = 0
while pos < end:
    assert pos + 48 <= end
    fields = struct.unpack("<4sHHIIIIQQQ", raw[pos:pos + 48])
    (magic, block_header, flags, count, rank_bytes, metadata_bytes,
     associations, first, last, checksum) = fields
    assert magic == b"BSP3" and block_header == 48 and 0 < count <= 1024
    meta_start = pos + block_header + rank_bytes
    payload = raw[meta_start:meta_start + metadata_bytes]
    assert len(payload) == metadata_bytes
    matched = [False] * count
    decoded_associations = 0
    cursor = 0
    descriptor_count, cursor = varint(payload, cursor)
    prior_descriptor = None
    for _ in range(descriptor_count):
        length, cursor = varint(payload, cursor)
        descriptor = payload[cursor:cursor + length]
        cursor += length
        assert len(descriptor) == length and length >= 7
        assert prior_descriptor is None or prior_descriptor < descriptor
        prior_descriptor = descriptor
        kind = descriptor[0]
        key_len = descriptor[1]
        assert length == key_len + 7
        key = descriptor[2:2 + key_len].decode("ascii")
        ante, phase, source, ordinal, descriptor_flags = \
            descriptor[2 + key_len:7 + key_len]
        member_count, cursor = varint(payload, cursor)
        assert member_count > 0
        record = -1
        for index in range(member_count):
            delta, cursor = varint(payload, cursor)
            record = delta if index == 0 else record + delta
            assert 0 <= record < count
            decoded_associations += 1
            if (kind, key, ante, phase, source) == want:
                matched[record] = True
    assert cursor == len(payload)
    assert decoded_associations == associations
    assert all(matched), "%s: expected descriptor %r missing from a record" % (path, want)
    seen_records += count
    pos = meta_start + metadata_bytes

assert pos == end and seen_records == records
PY
}

check_metadata "$OUT/tag-small.bspool" 1 "$TAG" 1 1 0
check_metadata "$OUT/tag-big.bspool" 1 "$TAG" 1 2 0
check_metadata "$OUT/charm.bspool" 1 "$TAG" 1 1 0
check_metadata "$OUT/charm.bspool" 2 "$LEGENDARY" 1 1 2
check_metadata "$OUT/boss.bspool" 2 "$LEGENDARY" 1 0 1

# Source is a real predicate, not just an annotation: the known Charm-reward
# members cannot satisfy the otherwise-identical Shop-source rule.
"./native/brainstorm_seed_pool$EXE" fixture "$OUT/snapshot.cfg" \
	"$OUT/charm-wrong-source.cfg" "$OUT/charm.txt" > "$OUT/wrong-source.fixture"
if awk '$2 == 1 { found=1 } END { exit !found }' "$OUT/wrong-source.fixture"; then
	echo "FAIL: a Charm reward was accepted as Shop source"; exit 1
fi

# Legacy A2 means the RNG stream Ante, not displayed Ante. Human A1 Boss is
# therefore accepted by legacy A2 and rejected by legacy A1.
"./native/brainstorm_seed_pool$EXE" fixture "$OUT/legacy-snapshot.cfg" \
	"$OUT/legacy-a2.cfg" "$OUT/legacy-boss.txt" > "$OUT/legacy-a2.fixture"
if awk '$2 != 1 { bad=1 } END { exit !bad }' "$OUT/legacy-a2.fixture"; then
	echo "FAIL: human A1 Boss was not accepted by legacy RNG-Ante 2"; exit 1
fi
"./native/brainstorm_seed_pool$EXE" fixture "$OUT/legacy-snapshot.cfg" \
	"$OUT/legacy-a1.cfg" "$OUT/legacy-boss.txt" > "$OUT/legacy-a1.fixture"
if awk '$2 == 1 { found=1 } END { exit !found }' "$OUT/legacy-a1.fixture"; then
	echo "FAIL: old Legendary 1..1 was reinterpreted as human A1"; exit 1
fi

# Refiltering the exact human pool through the equivalent legacy RNG-Ante rule
# proves both coordinate systems survive the .bspool header parser together.
"./native/brainstorm_seed_pool$EXE" refilter "$OUT/legacy-snapshot.cfg" \
	"$OUT/legacy-a2.cfg" "$OUT/legacy-boss.bspool" "$OUT/boss-roundtrip.bspool"
"./native/brainstorm_seed_pool$EXE" export "$OUT/boss-roundtrip.bspool" \
	"$OUT/boss-roundtrip.txt"
sort "$OUT/legacy-boss.txt" > "$OUT/boss.sorted"
sort "$OUT/boss-roundtrip.txt" > "$OUT/boss-roundtrip.sorted"
cmp "$OUT/boss.sorted" "$OUT/boss-roundtrip.sorted"
grep -a -q "^route_legendary $LEGENDARY 1 boss 1 boss 0 shop 1$" \
	"$OUT/boss-roundtrip.bspool"
grep -a -q "^legendary $LEGENDARY 2 2 0$" "$OUT/boss-roundtrip.bspool"
check_metadata "$OUT/boss-roundtrip.bspool" 2 "$LEGENDARY" 1 0 1

# Exercise the same cumulative exact-location route through the in-game native
# pool loader. No overlay filter is active, so every committed member must
# remain valid under the route inherited from the pool header.
{
	echo "session 1"; echo "threads 4"; echo "modelver 6"; echo "entropy 1"
	echo "soul 0"; echo "legendary -"; echo "neglegendary 0"; echo "tag -"
	echo "voucher -"; echo "voucherante 1"; echo "taganywhere 0"; echo "leganywhere 0"
	echo "matchany 0"; echo "jslot 1 - 0"; echo "jslot 2 - 0"; echo "jslot 3 - 0"
	echo "maslots 0 0 0 0 0 0 0 0"; echo "mapacks 0 0 0 0 0 0 0 0"; echo "packslots 2"
	echo "poolfile $(native_path "$OUT/boss-roundtrip.bspool")"
	grep -E '^(tagdef|vouchdef|vouchroute|vouchowned|jokerdef|boostdef|specialdef|check_[a-z0-9]+) ' \
		"$OUT/legacy-snapshot.cfg"
	echo "end"
} > "$OUT/overlay.cfg"
sed -n '1,500p' "$OUT/boss-roundtrip.txt" > "$OUT/overlay.seeds"
"./native/brainstorm_native_search$EXE" fixture "$OUT/overlay.cfg" \
	"$OUT/overlay.seeds" > "$OUT/overlay.fixture"
if awk '$2 != 1 { bad=1 } END { exit !bad }' "$OUT/overlay.fixture"; then
	echo "FAIL: in-game pool loader rejected an exact-location member"; exit 1
fi

SMALL_RECORDS=$(wc -l < "$OUT/tag-small.txt" | tr -d ' ')
BIG_RECORDS=$(wc -l < "$OUT/tag-big.txt" | tr -d ' ')
CHARM_RECORDS=$(wc -l < "$OUT/charm.txt" | tr -d ' ')
BOSS_RECORDS=$(wc -l < "$OUT/boss.txt" | tr -d ' ')
echo "PASS: exact tag phases, Legendary phases/sources, metadata, legacy RNG Antes, and header round trips agree (small=$SMALL_RECORDS big=$BIG_RECORDS charm=$CHARM_RECORDS boss=$BOSS_RECORDS)"
