#!/bin/sh
# Verify the generalized external pool engine against the established native
# Model-3 implementation over their shared A1-A8 semantics.
#
# Usage:
#   tests/seed_pool_equivalence.sh [native-snapshot.cfg] [seed-count]
#
# native_search.cfg is produced by Brainstorm whenever its native search runs.
# CI has no user snapshot, so it passes a synthetic one generated by
# tests/dump_native_fixtures.lua and overrides TAG with a tag that snapshot
# actually contains (the synthetic pool uses generic tag names).
set -eu

SNAPSHOT="${1:-native_search.cfg}"
COUNT="${2:-1000000}"
TAG="${TAG:-tag_rare}"
OUT="${TMPDIR:-/tmp}/brainstorm_seed_pool_equivalence"
mkdir -p "$OUT"

# Windows CI runs this same harness under Git Bash against the .exe builds.
case "$(uname -s)" in
	MINGW*|MSYS*|CYGWIN*) EXE=.exe; BUILD=native/build_windows.sh ;;
	*) EXE=; BUILD=native/build.sh ;;
esac

sh "$BUILD"

# The snapshot on disk may predate the current config protocol; the catalog
# data (pools/checks) is version-independent, so rewrite only the handshake.
cp "$SNAPSHOT" "$OUT/snapshot.cfg"
SNAPSHOT="$OUT/snapshot.cfg"
${CC:-clang} -O3 -DBRAINSTORM_VERIFY_OMEN_TRACE \
	-DBRAINSTORM_VERIFY_VOUCHER_RAW_CACHE \
	-Wall -Wno-unused-function -ffp-contract=off -pthread \
	-o "$OUT/seed_pool_compat$EXE" tests/seed_pool_compat.c -lm

{
	echo "poolver 1"
	echo "threads 1"
	echo "start 0"
	echo "count $COUNT"
	echo "checkpoint $COUNT"
	echo "chunk 16384"
	echo "resume 0"
	echo "format count"
	echo "tag_route collect"
	echo "tag $TAG 1 8 1"
	echo "legendary j_perkeo 1 8"
	echo "end"
} > "$OUT/criteria.cfg"

"$OUT/seed_pool_compat$EXE" "$SNAPSHOT" "$OUT/criteria.cfg" "$COUNT"
