"""Scoring workspace shared by the standalone and unified Seed Pool Program.

The browser holds selection drafts and renders bounded result pages. Jobs,
checkpoints, source verification, and scoring remain owned by the backend.
"""

STYLE = r'''
.score-layout{max-width:1180px;grid-template-columns:minmax(0,1fr)}.score-layout>.card{min-width:0}.score-layout .head{margin-bottom:12px}.score-help{max-width:76ch;line-height:1.55}
.score-toolbar{display:flex;gap:9px;flex-wrap:wrap;align-items:center;margin:12px 0}.score-toolbar .field{margin:0;flex:1;min-width:180px}
.score-layout input[type=number],.score-layout input[type=search]{width:100%;min-height:42px;padding:9px 11px;border:1px solid #3b4159;border-radius:10px;background:#0f1119;color:var(--text);font:inherit}
.score-pools{max-height:480px;overflow:auto;display:grid;gap:8px;padding:2px;margin:12px 0}.score-pool{border:1px solid #30364b;border-radius:11px;background:#10131c}.score-pool.selected{border-color:#8c77d4;background:#191526}
.score-pick{display:flex;gap:10px;align-items:flex-start;padding:12px;cursor:pointer}.score-pick input,.score-check input{width:17px;height:17px;flex:0 0 auto;accent-color:var(--purple);margin:2px 0 0}.score-pick>span{flex:1;min-width:0}.score-pick b,.score-pick small{display:block;overflow-wrap:anywhere}.score-pick small{color:var(--muted);margin-top:3px;line-height:1.4}.score-pick .count{flex:0 0 auto;font-size:12px}
.score-starting{padding:0 12px 12px 39px}.score-starting p{margin:0 0 10px;font-size:12px;line-height:1.5}.score-starting .field{margin:0}.score-fields{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.score-fields .field{margin:0}.score-fields.two-fields{grid-template-columns:repeat(2,minmax(0,1fr))}
.score-check{display:flex;gap:9px;align-items:flex-start;line-height:1.5;margin:12px 0}.score-check span{display:block}.score-check small{display:block;color:var(--muted);font-weight:400}.score-empty{padding:15px;border:1px dashed #41455b;border-radius:10px;color:var(--muted);font-size:13px}.score-summary{color:var(--muted);font-size:13px;min-height:20px}.score-note{margin:10px 0;color:var(--muted);font-size:12px;line-height:1.55}
.score-progress{width:100%;height:12px;accent-color:#9177dd;margin-top:12px}.score-progress-pools{display:grid;gap:7px;margin-top:12px}.score-progress-pool{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;padding:10px;border:1px solid #30364b;border-radius:9px;background:#10131c;font-size:12px}.score-progress-pool b{overflow-wrap:anywhere}.score-progress-pool small{display:block;color:var(--muted);margin-top:4px;line-height:1.4}.score-progress-pool .error{grid-column:1/-1;margin:0;font-size:12px}
.score-table-wrap{overflow:auto;max-width:100%;border:1px solid #30364b;border-radius:10px;margin-top:12px}.score-table{width:100%;border-collapse:collapse;font-size:12px;font-variant-numeric:tabular-nums}.score-table th,.score-table td{padding:11px 12px;text-align:left;border-bottom:1px solid #2b3042;vertical-align:top}.score-table th{background:#202032;color:#d8d2e6;white-space:nowrap}.score-table tbody tr:last-child td{border-bottom:0}.score-table .score-value{text-align:right;white-space:nowrap}.score-table .score-seed{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;white-space:nowrap;color:#f2ebff}.score-table .score-route{min-width:240px;max-width:520px;line-height:1.55}.score-table .score-source-cell{min-width:160px;overflow-wrap:anywhere}.score-table details>summary{cursor:pointer;color:#c5b6fa}.score-table details>p{margin:7px 0}.score-reference{display:block;color:#9be0b0;font-size:10px;white-space:nowrap}
.score-columns{display:flex;gap:8px 18px;flex-wrap:wrap}.score-columns .score-check{margin:8px 0;font-size:12px}.score-downloads a{display:inline-block;padding:8px 12px;border:1px solid #3b425b;border-radius:9px;color:#d7d2df;font-size:12px;text-decoration:none}.score-downloads a:hover{border-color:#8c77d4}.score-jobs{border-top:1px solid #30364b;margin-top:20px;padding-top:15px}.score-jobs h3{margin:0;font-size:14px}.score-status-title{font-size:16px}.score-layout fieldset{min-width:0}.score-layout button,.score-layout a,.score-layout select{touch-action:manipulation}
@media(max-width:760px){.score-fields,.score-fields.two-fields{grid-template-columns:1fr}.score-starting{padding-left:12px}.score-pick{flex-wrap:wrap}.score-pick .count{margin-left:27px}.score-progress-pool{grid-template-columns:1fr}.score-table th,.score-table td{padding:9px 8px}.score-table{font-size:11px}.score-table-wrap{margin-left:-5px;margin-right:-5px}}
'''

WORKSPACE = r'''
<div id="scoreWorkspace" class="stack score-layout" role="tabpanel" aria-labelledby="scoreModeBtn" hidden>
 <section class="card">
  <div class="head"><span class="step">1</span><div><h2>Choose pools to score</h2><p class="copy score-help">Rank seeds by expected scaling. Each pool keeps its own starting point; results include a combined leaderboard and a leaderboard for each pool.</p></div></div>
  <fieldset id="scoreInputs" class="choicegroup">
   <div class="score-toolbar"><div class="field"><label for="scorePoolSearch">Find a pool</label><input id="scorePoolSearch" type="search" placeholder="Filter by name" autocomplete="off"></div><button id="scoreRefreshPools" class="ghost">Refresh pools</button></div>
   <div class="score-toolbar"><button id="scoreSelectVisible" class="small">Select visible pools</button><button id="scoreClearSelection" class="small ghost">Clear selection</button></div>
   <div class="score-summary" id="scoreSelectionSummary" aria-live="polite">Choose up to 32 pools.</div>
   <div id="scorePoolChoices" class="score-pools"></div>
   <p class="score-note score-help">Small second tag → first copy at Big. Big second tag → first copy at Boss, in the same Ante. Saved tag rules supply this automatically; otherwise choose a starting point for that pool.</p>
   <label class="score-check" for="scoreRecordMissing"><input id="scoreRecordMissing" type="checkbox"><span>Record missing tag placements<small>Scoring needs both tag types through original Ante 38. Recording uses the matching game profile; your source pools stay unchanged.</small></span></label>
   <details class="advanced"><summary>Scoring options</summary><div class="advancedbody">
    <div class="score-fields">
     <div class="field"><label for="scoreTop">Seeds per leaderboard</label><input id="scoreTop" type="number" min="1" max="10000" step="1" value="1000"></div>
     <div class="field"><label for="scoreWorkers">Scoring workers</label><input id="scoreWorkers" type="number" min="1" max="16" step="1" value="1"><span class="hint">More workers use more of this computer.</span></div>
     <div class="field"><label for="scoreReference">Reference score (optional)</label><input id="scoreReference" type="number" min="0" step="any" placeholder="For example, 721.77"><span class="hint">Marks scores above this value.</span></div>
    </div>
    <label class="score-check" for="scoreExportAll"><input id="scoreExportAll" type="checkbox"><span>Also export every seed's tags, score, and route<small>Larger files and extra route calculations. Pool history and source metadata are retained even when this is off.</small></span></label>
   </div></details>
  </fieldset>
  <div class="score-toolbar"><button id="scoreStartBtn" class="go" disabled>Score selected pools</button></div>
  <div id="scoreSetupError" class="error" role="alert"></div>
  <div class="score-jobs"><h3>Saved runs</h3><p class="score-note">Reopen results or resume an interrupted run. Progress is saved on this computer.</p><div class="score-toolbar"><div class="field"><label for="scoreJobSelect">Scoring run</label><select id="scoreJobSelect"><option value="">No saved runs loaded</option></select></div><button id="scoreRefreshJobs" class="ghost">Refresh runs</button></div><div id="scoreJobsError" class="error" role="alert"></div></div>
 </section>
 <section class="card" id="scoreRunCard" hidden>
  <div class="head"><span class="step">2</span><div><h2 id="scoreRunTitle">Scoring run</h2><p id="scoreRunIdentity" class="copy"></p></div></div>
  <div id="scoreRunStatus" class="score-status-title" role="status" aria-live="polite"></div>
  <div id="scoreRunDetail" class="score-note"></div><progress id="scoreProgress" class="score-progress" max="1" aria-label="Seeds processed" hidden></progress>
  <div class="score-toolbar"><button id="scoreCancelBtn" class="cancel" hidden>Stop and save progress</button><button id="scoreResumeBtn" class="go" hidden>Resume scoring</button><button id="scoreRetryStatus" class="ghost" hidden>Refresh status</button></div>
  <div id="scoreRunError" class="error" role="alert"></div>
  <details class="advanced"><summary>Progress by pool</summary><div class="advancedbody"><div id="scorePoolProgress" class="score-progress-pools"></div></div></details>
 </section>
 <section class="card" id="scoreResultsCard" hidden>
  <div class="head"><span class="step">3</span><div><h2>Leaderboard</h2><p class="copy score-help">Best route for each seed, ordered by scaling score. Add the Redeem route column to inspect a route.</p></div></div>
  <div class="score-toolbar"><div class="field"><label for="scoreResultPool">Show results for</label><select id="scoreResultPool"><option value="">All selected pools</option></select></div><button id="scoreRefreshResults" class="ghost">Refresh results</button></div>
  <p id="scoreResultsStatus" class="score-note" role="status" aria-live="polite"></p>
  <details class="advanced"><summary>Show more columns</summary><div class="advancedbody score-columns">
   <label class="score-check" for="scoreColumnPool"><input id="scoreColumnPool" type="checkbox"><span>Source pool</span></label>
   <label class="score-check" for="scoreColumnCopy"><input id="scoreColumnCopy" type="checkbox"><span>First copy</span></label>
   <label class="score-check" for="scoreColumnTags"><input id="scoreColumnTags" type="checkbox"><span>Starting tags</span></label>
   <label class="score-check" for="scoreColumnRoute"><input id="scoreColumnRoute" type="checkbox"><span>Redeem route</span></label>
  </div></details>
  <div id="scoreTableWrap" class="score-table-wrap" tabindex="0" role="region" aria-label="Scoring leaderboard"><table class="score-table"><thead id="scoreTableHead"></thead><tbody id="scoreTableBody"></tbody></table></div>
  <div class="pager"><button id="scorePrevPage" class="small ghost" disabled>Previous</button><span id="scorePageLabel"></span><button id="scoreNextPage" class="small ghost" disabled>Next</button></div>
  <p class="score-note score-help">Hiero and Petro timings refer to the original Ante sequence. If both use the same boundary, take Hieroglyph first, then Petroglyph. These are model timings; check voucher availability and the route in-game.</p>
  <p class="score-note score-help">Scaling score uses the supplied probability model, with starting Blueprint + Brainstorm normalized to 1. Compare runs that use the same assumptions.</p>
  <div id="scoreResultsError" class="error" role="alert"></div>
  <div id="scoreDownloads" class="score-toolbar score-downloads" aria-label="Download scoring results"></div>
 </section>
</div>
'''

SCRIPT = r'''
const scoreState={pools:[],poolSignatures:new Map(),selected:new Map(),drafts:new Map(),descriptions:new Map(),pendingDescriptions:new Map(),descriptionQueue:[],descriptionActive:0,descriptionRevision:0,poolNodes:new Map(),jobs:[],job:null,jobId:"",jobRevision:0,statusRevision:0,resultRevision:0,result:null,resultPool:"",offset:0,pageSize:50,busy:false,pollTimer:0,lastResultsAt:0,jobsRevision:0};
const scoreActiveStates=new Set(["queued","preparing","running","finalizing","cancelling"]);
const scoreStatusNames={queued:"Waiting to start",preparing:"Preparing tag data",running:"Scoring seeds",finalizing:"Saving leaderboards",cancelling:"Stopping and saving progress",interrupted:"Stopped — progress saved",completed:"Scoring complete",failed:"Scoring stopped with an error"};
function scoreElement(tag,text,className){const node=document.createElement(tag);if(text!=null)node.textContent=text;if(className)node.className=className;return node}
function scoreMessage(id,error){$(id).textContent=error?(error.message||String(error)):""}
function scorePosition(value){return typeof value==="string"?value:value&&typeof value.position==="string"?value.position:""}
function scoreFirstCopy(value){const match=/^A([1-9]\d?)(S|B)$/i.exec(scorePosition(value));return match?`A${Number(match[1])}${match[2].toUpperCase()==="S"?"B":"Boss"}`:""}
function scoreLocation(value){const text=scorePosition(value),match=/^A([1-9]\d?)(S|B|Boss)$/i.exec(text);return match?`A${Number(match[1])} ${match[2].toLowerCase()==="s"?"Small":match[2].toLowerCase()==="b"?"Big":"Boss"}`:text||"—"}
function scoreTagName(value){return value==="negative"||value==="neg"?"Negative":value==="rare"?"Rare":value==="both"?"Both (same Ante)":"—"}
function scorePositionSelect(value,boss=false){const node=scoreElement("select");node.append(new Option("Choose a position", ""));for(let ante=1;ante<=38;ante++)for(const phase of boss?["S","B","Boss"]:["S","B"])node.append(new Option(scoreLocation(`A${ante}${phase}`),`A${ante}${phase}`));node.value=value||"";return node}
function scoreField(label,control,id){const field=scoreElement("div",null,"field"),title=scoreElement("label",label);control.id=id;title.htmlFor=id;field.append(title,control);return field}
function scorePoolDraft(name){if(!scoreState.drafts.has(name))scoreState.drafts.set(name,{mode:"auto",second_tag:"",baseline_copy:"",second_tag_type:""});return scoreState.drafts.get(name)}
function scoreSavedStart(description){return description&&scorePosition(description.second_tag)?{second:scorePosition(description.second_tag),copy:description.baseline_copy||scoreFirstCopy(description.second_tag),tag:description.second_tag.tag||""}:description&&description.baseline_copy?{second:"",copy:description.baseline_copy,tag:""}:null}
function scorePoolUnavailable(pool){return pool.error|| (pool.complete===false?"Finish this pool before scoring.":pool.metadata_capable===false?"This pool needs recorded event data before scoring.":"")}
function scoreFilteredPools(){const query=$("scorePoolSearch").value.trim().toLowerCase();return scoreState.pools.filter(pool=>!query||String(pool.name).toLowerCase().includes(query))}
function scoreUpdateSelection(){const names=[...scoreState.selected.keys()],total=names.reduce((count,name)=>count+Number(scoreState.selected.get(name).records||0),0);$("scoreSelectionSummary").textContent=names.length?`${names.length} pool${names.length===1?"":"s"} selected · ${fmt(total)} saved seeds` :"Choose up to 32 pools.";const active=scoreState.jobs.some(job=>scoreActiveStates.has(job.status));$("scoreStartBtn").disabled=scoreState.busy||!names.length||active;$("scoreStartBtn").textContent=active?"Scoring run in progress":"Score selected pools";$("scoreInputs").disabled=scoreState.busy;$("scoreJobSelect").disabled=scoreState.busy;$("scoreRefreshJobs").disabled=scoreState.busy;$("scoreSelectVisible").disabled=scoreState.busy;$("scoreClearSelection").disabled=scoreState.busy||!names.length}
function refreshScorePools(payload){const pools=Array.isArray(payload)?payload:payload&&Array.isArray(payload.pools)?payload.pools:workflowState.pools;scoreState.pools=Array.isArray(pools)?pools:[];let changed=false;for(const pool of scoreState.pools){const signature=JSON.stringify(pool);if(scoreState.poolSignatures.has(pool.name)&&scoreState.poolSignatures.get(pool.name)!==signature){scoreState.descriptions.delete(pool.name);changed=true}scoreState.poolSignatures.set(pool.name,signature)}if(changed)scoreState.descriptionRevision++;const available=new Map(scoreState.pools.map(pool=>[pool.name,pool]));let removed=0;for(const name of scoreState.selected.keys()){if(!available.has(name)||scorePoolUnavailable(available.get(name))){scoreState.selected.delete(name);removed++}else scoreState.selected.set(name,available.get(name))}if(removed)scoreMessage("scoreSetupError",`${removed} selected pool${removed===1?" is":"s are"} unavailable in the current list. Refresh and check the selection before scoring.`);for(const name of scoreState.descriptions.keys())if(!available.has(name))scoreState.descriptions.delete(name);renderScorePools();for(const name of scoreState.selected.keys())scoreDescribePool(name)}
function renderScorePools(){const holder=$("scorePoolChoices"),pools=scoreFilteredPools();holder.replaceChildren();scoreState.poolNodes.clear();if(!pools.length)holder.append(scoreElement("div",scoreState.pools.length?"No pools match this name.":"No pools available. Create a pool or refresh the list.","score-empty"));for(const pool of pools){const selected=scoreState.selected.has(pool.name),card=scoreElement("div",null,`score-pool${selected?" selected":""}`),label=scoreElement("label",null,"score-pick"),check=scoreElement("input"),body=scoreElement("span"),settings=scoreElement("div",null,"score-starting");check.type="checkbox";check.checked=selected;check.disabled=!!scorePoolUnavailable(pool);check.setAttribute("aria-label",`Score ${pool.name}`);body.append(scoreElement("b",pool.name));if(scorePoolUnavailable(pool))body.append(scoreElement("small",scorePoolUnavailable(pool)));label.append(check,body,scoreElement("span",`${fmt(pool.records)} seeds`,"count"));settings.hidden=!selected;card.append(label,settings);holder.append(card);scoreState.poolNodes.set(pool.name,{card,settings,check,index:scoreState.poolNodes.size});check.onchange=()=>scoreChoosePool(pool.name,check.checked);if(selected)renderScorePoolSettings(pool.name)}scoreUpdateSelection()}
function scoreChoosePool(name,selected){if(scoreState.busy)return;scoreMessage("scoreSetupError","");const pool=scoreState.pools.find(row=>row.name===name);if(selected&&pool&&!scorePoolUnavailable(pool)){if(!scoreState.selected.has(name)&&scoreState.selected.size>=32){scoreMessage("scoreSetupError","Choose up to 32 pools in one run.");const nodes=scoreState.poolNodes.get(name);if(nodes)nodes.check.checked=false;return}scoreState.selected.set(name,pool);scorePoolDraft(name);scoreDescribePool(name)}else scoreState.selected.delete(name);selected=scoreState.selected.has(name);const nodes=scoreState.poolNodes.get(name);if(nodes){nodes.card.className=`score-pool${selected?" selected":""}`;nodes.settings.hidden=!selected;nodes.check.checked=selected;if(selected)renderScorePoolSettings(name)}scoreUpdateSelection()}
function scoreDescribePool(name){if(scoreState.descriptions.has(name)||scoreState.pendingDescriptions.has(name))return;scoreState.pendingDescriptions.set(name,true);scoreState.descriptionQueue.push(name);scoreDrainDescriptions()}
function scoreDrainDescriptions(){while(scoreState.descriptionActive<3&&scoreState.descriptionQueue.length){const name=scoreState.descriptionQueue.shift(),revision=scoreState.descriptionRevision;scoreState.descriptionActive++;Promise.resolve().then(()=>api("/api/score/describe",{source:name})).then(value=>{if(revision===scoreState.descriptionRevision)scoreState.descriptions.set(name,value)},error=>{if(revision===scoreState.descriptionRevision)scoreState.descriptions.set(name,{error:error.message||String(error)})}).finally(()=>{scoreState.pendingDescriptions.delete(name);scoreState.descriptionActive--;if(scoreState.selected.has(name)){if(revision!==scoreState.descriptionRevision)scoreDescribePool(name);renderScorePoolSettings(name)};scoreDrainDescriptions()})}}
function renderScorePoolSettings(name){
 const nodes=scoreState.poolNodes.get(name);if(!nodes||!scoreState.selected.has(name))return;
 const holder=nodes.settings,focusId=holder.contains(document.activeElement)?document.activeElement.id:"",description=scoreState.descriptions.get(name),draft=scorePoolDraft(name),saved=scoreSavedStart(description),prefix=`scorePool${nodes.index}`;
 holder.replaceChildren();
 if(!description){holder.append(scoreElement("p","Reading saved starting point…","hint"));return}
 if(description.error){holder.append(scoreElement("p",description.error,"error"));const retry=scoreElement("button","Retry saved data","small ghost");retry.onclick=()=>{scoreState.descriptions.delete(name);scoreDescribePool(name);renderScorePoolSettings(name)};holder.append(retry);return}
 if(saved){holder.append(scoreElement("p",`${saved.second?"Saved second tag: "+scoreLocation(saved.second)+(saved.tag?" "+scoreTagName(saved.tag):"")+". ":""}First copy: ${scoreLocation(saved.copy)}.`));return}
 const mode=scoreElement("select");mode.append(new Option("Choose a starting point","auto"),new Option("Choose the second tag","second"),new Option("Set the first-copy shop","copy"));mode.value=draft.mode;
 const fields=scoreElement("div",null,"score-fields two-fields");fields.append(scoreField("Starting point",mode,prefix+"Mode"));mode.onchange=()=>{draft.mode=mode.value;renderScorePoolSettings(name)};
 let firstCopy="";
 if(draft.mode==="auto")holder.append(scoreElement("p","No saved second-tag result. Choose this pool's second tag or first-copy shop.","hint"));
 else if(draft.mode==="second"){
  const second=scorePositionSelect(draft.second_tag);fields.append(scoreField("Second-tag position",second,prefix+"Second"));firstCopy=scoreFirstCopy(draft.second_tag);second.onchange=()=>{draft.second_tag=second.value;renderScorePoolSettings(name)};
  const type=scoreElement("select");for(const [value,label] of [["","Use recorded tag type"],["negative","Negative"],["rare","Rare"]])type.append(new Option(label,value));type.value=draft.second_tag_type;type.onchange=()=>{draft.second_tag_type=type.value};fields.append(scoreField("Second-tag type (optional)",type,prefix+"Type"));
 }else{
  const copy=scorePositionSelect(draft.baseline_copy,true);fields.append(scoreField("First-copy shop",copy,prefix+"Copy"));firstCopy=draft.baseline_copy;copy.onchange=()=>{draft.baseline_copy=copy.value;renderScorePoolSettings(name)};
 }
 holder.append(fields);if(firstCopy)holder.append(scoreElement("p",`First copy: ${scoreLocation(firstCopy)}.`,"score-note"));
 if(focusId){const control=document.getElementById(focusId);if(control)control.focus({preventScroll:true})}
}
function scoreInteger(id,label,min,max){const text=$(id).value.trim(),value=Number(text);if(!text||!Number.isInteger(value)||value<min||value>max)throw Error(`${label} must be a whole number from ${min} to ${max}.`);return value}
function scoreRequest(){if(!scoreState.selected.size)throw Error("Choose at least one pool.");if(scoreState.selected.size>32)throw Error("Choose up to 32 pools in one run.");const pools=[];for(const name of scoreState.selected.keys()){const draft=scorePoolDraft(name),description=scoreState.descriptions.get(name),saved=scoreSavedStart(description),row={source:name};if(!description)throw Error(`Still reading the starting point for ${name}. Try again in a moment.`);if(description.error)throw Error(`${name}: ${description.error}`);if(saved){pools.push(row);continue}if(draft.mode==="auto"){if(!saved)throw Error(`Choose the second tag or first-copy shop for ${name}.`)}else if(draft.mode==="second"){if(!scoreFirstCopy(draft.second_tag))throw Error(`Choose the second-tag position for ${name}.`);row.second_tag=draft.second_tag;if(draft.second_tag_type)row.second_tag_type=draft.second_tag_type}else{if(!/^A([1-9]|[12]\d|3[0-8])(S|B|Boss)$/.test(draft.baseline_copy))throw Error(`Choose the first-copy shop for ${name}.`);row.baseline_copy=draft.baseline_copy}pools.push(row)}const request={pools,workers:scoreInteger("scoreWorkers","Scoring workers",1,16),top:scoreInteger("scoreTop","Leaderboard size",1,10000),record_missing:$("scoreRecordMissing").checked,export_all:$("scoreExportAll").checked};const reference=$("scoreReference").value.trim();if(reference){const number=Number(reference);if(!Number.isFinite(number)||number<=0)throw Error("Reference score must be a positive number.");request.reference_score=number}return request}
async function startScoreRun(){if(scoreState.busy)return;if(scoreState.jobs.some(job=>scoreActiveStates.has(job.status))){scoreMessage("scoreSetupError","A scoring run is already in progress. Open it under Saved runs to view or stop it.");return}scoreMessage("scoreSetupError","");let request;try{request=scoreRequest()}catch(error){scoreMessage("scoreSetupError",error);return}scoreState.busy=true;scoreUpdateSelection();try{const job=await api("/api/score/start",request);await selectScoreJob(job.job_id,job);refreshScoreJobs(false);$("scoreRunCard").scrollIntoView({block:"start",behavior:"smooth"})}catch(error){scoreMessage("scoreSetupError",error)}finally{scoreState.busy=false;scoreUpdateSelection()}}
function scoreJobLabel(job){const date=typeof job.created_at==="number"?new Date(job.created_at*1000):new Date(job.created_at),when=Number.isNaN(date.getTime())?"":date.toLocaleString();return `${when?when+" · ":""}${scoreStatusNames[job.status]||job.status||"Saved run"} · ${(job.pools||[]).length} pool${(job.pools||[]).length===1?"":"s"}`}
function renderScoreJobs(){const picker=$("scoreJobSelect");picker.replaceChildren(new Option(scoreState.jobs.length?"Choose a saved run":"No saved runs",""));for(const job of scoreState.jobs)picker.append(new Option(scoreJobLabel(job),job.job_id));picker.value=scoreState.jobs.some(job=>job.job_id===scoreState.jobId)?scoreState.jobId:"";scoreUpdateSelection()}
async function refreshScoreJobs(selectLatest=true){const revision=++scoreState.jobsRevision;scoreMessage("scoreJobsError","");try{const response=await api("/api/score/jobs");if(revision!==scoreState.jobsRevision)return;scoreState.jobs=Array.isArray(response)?response:response.jobs||[];renderScoreJobs();if(selectLatest&&!scoreState.jobId&&scoreState.jobs.length){const job=scoreState.jobs.find(row=>scoreActiveStates.has(row.status))||scoreState.jobs[0];await selectScoreJob(job.job_id)}}catch(error){if(revision===scoreState.jobsRevision)scoreMessage("scoreJobsError",error)}}
function scoreClearPoll(){clearTimeout(scoreState.pollTimer);scoreState.pollTimer=0}
function scoreSchedulePoll(delay=1500){scoreClearPoll();if(scoreState.jobId)scoreState.pollTimer=setTimeout(()=>pollScoreJob(),delay)}
async function selectScoreJob(id,known){if(!id)return;scoreClearPoll();scoreState.jobRevision++;scoreState.resultRevision++;scoreState.jobId=id;scoreState.job=null;scoreState.result=null;scoreState.resultPool="";scoreState.offset=0;scoreState.lastResultsAt=0;$("scoreResultPool").value="";$("scoreResultsCard").hidden=true;$("scoreRunCard").hidden=false;$("scoreRunStatus").textContent="Loading saved run…";$("scoreRunDetail").textContent="";$("scoreRunError").textContent="";$("scoreCancelBtn").hidden=true;$("scoreResumeBtn").hidden=true;$("scoreProgress").hidden=true;renderScoreTable();renderScoreJobs();if(known&&known.job_id===id){renderScoreJob(known);await refreshScoreResults();if(scoreActiveStates.has(known.status))scoreSchedulePoll()}else await pollScoreJob()}
async function pollScoreJob(){const id=scoreState.jobId,revision=scoreState.jobRevision,statusRevision=++scoreState.statusRevision;if(!id||scoreState.busy)return;scoreClearPoll();try{const job=await api(`/api/score/status?job_id=${encodeURIComponent(id)}`);if(id!==scoreState.jobId||revision!==scoreState.jobRevision||statusRevision!==scoreState.statusRevision)return;renderScoreJob(job);if(!scoreState.result||!scoreActiveStates.has(job.status)||Date.now()-scoreState.lastResultsAt>=5000)await refreshScoreResults();if(id===scoreState.jobId&&revision===scoreState.jobRevision&&statusRevision===scoreState.statusRevision&&scoreActiveStates.has(job.status))scoreSchedulePoll()}catch(error){if(id!==scoreState.jobId||revision!==scoreState.jobRevision||statusRevision!==scoreState.statusRevision)return;scoreMessage("scoreRunError",`Could not refresh status: ${error.message||error}. The run may still be working.`);$("scoreRetryStatus").hidden=false;scoreSchedulePoll(5000)}}
function renderScoreJob(job){scoreState.job=job;$("scoreRunCard").hidden=false;$("scoreRunIdentity").textContent=scoreJobLabel(job);$("scoreRunStatus").textContent=scoreStatusNames[job.status]||"Checking run status";const done=Number(job.completed_records||0),total=Number(job.total_records||0),active=scoreActiveStates.has(job.status);$("scoreRunDetail").textContent=`${fmt(done)}${total?" of "+fmt(total):""} seeds processed · ${fmt(job.scored)} scored · ${fmt(job.no_valid_route)} without a valid route.${job.phase&&job.phase!==job.status?" "+scorePhaseName(job.phase):""}`;const bar=$("scoreProgress");bar.hidden=!total;bar.max=total||1;bar.value=Math.min(total,done);$("scoreCancelBtn").hidden=!active;$("scoreCancelBtn").disabled=job.status==="cancelling";$("scoreCancelBtn").textContent=job.status==="cancelling"?"Saving progress…":"Stop and save progress";$("scoreResumeBtn").hidden=!job.can_resume;$("scoreResumeBtn").disabled=false;$("scoreRetryStatus").hidden=true;scoreMessage("scoreRunError",job.error||"");const holder=$("scorePoolProgress");holder.replaceChildren();for(const pool of job.pools||[]){const item=scoreElement("div",null,"score-progress-pool"),label=scoreElement("div");label.append(scoreElement("b",pool.label||pool.source),scoreElement("small",`${scoreStatusNames[pool.status]||pool.status||"Waiting"} · First copy ${scoreLocation(pool.baseline_copy)}`));item.append(label,scoreElement("span",`${fmt(pool.completed_records)} / ${fmt(pool.records)} seeds`));if(pool.error)item.append(scoreElement("div",pool.error,"error"));holder.append(item)}const selected=scoreState.resultPool,picker=$("scoreResultPool");picker.replaceChildren(new Option("All selected pools",""));for(const pool of job.pools||[])picker.append(new Option(pool.label||pool.source,pool.pool_id));picker.value=(job.pools||[]).some(pool=>pool.pool_id===selected)?selected:"";if(picker.value!==selected){scoreState.resultPool="";scoreState.offset=0;scoreState.resultRevision++}renderScoreDownloads();const index=scoreState.jobs.findIndex(row=>row.job_id===job.job_id);if(index>=0)scoreState.jobs[index]=job;else scoreState.jobs.unshift(job);renderScoreJobs()}
function scorePhaseName(phase){return {preparing:"Preparing tag data.",recording_tags:"Recording missing tag placements.",verifying_source:"Checking source pools.",verifying_output:"Checking recorded tag data.",scoring:"Calculating routes.",leaderboards:"Ranking distinct seeds.",exporting_tags:"Saving tag placements.",exporting_scores:"Saving detailed scores.",exporting:"Saving result files.",completed:"Results saved."}[phase]||""}
async function changeScoreRun(action){const job=scoreState.job,id=scoreState.jobId,revision=scoreState.jobRevision;if(!job||scoreState.busy)return;scoreClearPoll();scoreState.statusRevision++;scoreState.resultRevision++;scoreState.busy=true;scoreUpdateSelection();const button=action==="cancel"?$("scoreCancelBtn"):$("scoreResumeBtn");button.disabled=true;scoreMessage("scoreRunError","");try{const result=await api(`/api/score/${action}`,{job_id:id});if(id!==scoreState.jobId||revision!==scoreState.jobRevision)return;renderScoreJob(result);await refreshScoreResults();if(scoreActiveStates.has(result.status))scoreSchedulePoll()}catch(error){if(id===scoreState.jobId&&revision===scoreState.jobRevision){scoreMessage("scoreRunError",`Could not confirm ${action==="cancel"?"stop request":"resume request"}: ${error.message||error}. Checking the saved run status.`);button.disabled=false;$("scoreRetryStatus").hidden=false;scoreSchedulePoll()}}finally{scoreState.busy=false;scoreUpdateSelection()}}
function scoreVoucher(value){if(!Number.isInteger(value)||value<1)return "—";return value>38?"After original A38":`Before original A${value}`}
function scoreRouteText(step,index){const tags=[step.neg_label,step.rare_label].filter(Boolean).join(" + "),shop=step.redeem_shop_desc||step.redeem_shop||"";return `${index+1}. ${tags||"Redeem"}${shop?"; redeem at "+shop:""}${step.final?" (final)":""}`}
function renderScoreTable(){const result=scoreState.result,rows=result&&Array.isArray(result.rows)?result.rows:[],pool=$("scoreColumnPool").checked,copy=$("scoreColumnCopy").checked,tags=$("scoreColumnTags").checked,route=$("scoreColumnRoute").checked,columns=["Rank","Seed","Scaling score","Hiero","Petro"];if(pool)columns.push("Source pool");if(copy)columns.push("First copy");if(tags)columns.push("Starting tags");if(route)columns.push("Redeem route");$("scoreTableHead").innerHTML="<tr>"+columns.map(title=>`<th scope="col">${title}</th>`).join("")+"</tr>";const reference=scoreState.job&&scoreState.job.request&&scoreState.job.request.reference_score;$("scoreTableBody").innerHTML=rows.length?rows.map((row,index)=>{const cells=[`<td>${fmt(row.position||scoreState.offset+index+1)}</td>`,`<td class="score-seed">${esc(row.seed)}</td>`,`<td class="score-value">${typeof row.score==="number"&&Number.isFinite(row.score)?row.score.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):"—"}${typeof reference==="number"&&row.score>reference?'<small class="score-reference">Above reference</small>':""}</td>`,`<td>${scoreVoucher(row.hieroglyph_before_ante)}</td>`,`<td>${scoreVoucher(row.petroglyph_before_ante)}</td>`];if(pool)cells.push(`<td class="score-source-cell">${esc(row.pool_label||row.pool_id||"—")}</td>`);if(copy)cells.push(`<td>${esc(scoreLocation(row.baseline_copy))}</td>`);if(tags)cells.push(`<td>First: ${esc(scoreTagName(row.first_tag_type))}<br>Second: ${esc(scoreTagName(row.second_tag_type))}${row.second_tag?" · "+esc(scoreLocation(row.second_tag)):""}</td>`);if(route){const steps=Array.isArray(row.route)?row.route:[];cells.push(`<td class="score-route">${steps.length?'<details><summary>Show route</summary>'+steps.map((step,i)=>`<p>${esc(scoreRouteText(step,i))}</p>`).join("")+"</details>":"—"}</td>`)}return "<tr>"+cells.join("")+"</tr>"}).join(""):`<tr><td colspan="${columns.length}">${result?"No scored seeds in this view yet.":"Loading results…"}</td></tr>`;const total=Number(result&&result.total||0),first=rows.length?Number(result.offset||0)+1:0,last=first?first+rows.length-1:0;$("scorePageLabel").textContent=`${fmt(first)}–${fmt(last)} of ${fmt(total)}`;$("scorePrevPage").disabled=!result||Number(result.offset||0)<=0;$("scoreNextPage").disabled=!result||Number(result.offset||0)+rows.length>=total;renderScoreDownloads()}
async function refreshScoreResults(){const id=scoreState.jobId,jobRevision=scoreState.jobRevision,pool=scoreState.resultPool,offset=scoreState.offset,revision=++scoreState.resultRevision;if(!id)return;$("scoreResultsCard").hidden=false;$("scoreRefreshResults").disabled=true;scoreMessage("scoreResultsError","");const params=new URLSearchParams({job_id:id,scope:pool||"combined",limit:String(scoreState.pageSize),offset:String(offset)});try{const result=await api(`/api/score/results?${params}`);if(id!==scoreState.jobId||jobRevision!==scoreState.jobRevision||revision!==scoreState.resultRevision)return;scoreState.result=result;scoreState.lastResultsAt=Date.now();const active=scoreState.job&&scoreActiveStates.has(scoreState.job.status);$("scoreResultsStatus").textContent=active?"The leaderboard appears after all seeds and source data are checked.":scoreState.job&&scoreState.job.status==="completed"?"Final results for this run.":scoreState.job&&scoreState.job.can_resume?"Progress is saved. Resume to finish the leaderboard.":"No final leaderboard is available for this run. Review the run status above.";renderScoreTable()}catch(error){if(id===scoreState.jobId&&revision===scoreState.resultRevision)scoreMessage("scoreResultsError",error)}finally{if(id===scoreState.jobId&&revision===scoreState.resultRevision)$("scoreRefreshResults").disabled=false}}
function renderScoreDownloads(){const holder=$("scoreDownloads"),job=scoreState.job;holder.replaceChildren();if(!job)return;for(const download of job.downloads||[]){if(download.pool_id&&download.pool_id!==scoreState.resultPool)continue;if(!download.pool_id&&scoreState.resultPool&&["leaderboard_csv","leaderboard_json"].includes(download.kind))continue;if(typeof download.filename!=="string"||!download.filename)continue;const params=new URLSearchParams({job_id:job.job_id,filename:download.filename});const link=scoreElement("a",download.label||download.kind);link.href=apiPath(`/api/score/download?${params}`);link.setAttribute("download","");holder.append(link)}}
function showScoreWorkspace(){refreshScorePools(workflowState.pools);refreshScoreJobs();if(scoreState.jobId)pollScoreJob()}
async function scoreCreatedPools(names){if(scoreState.busy)return;showMode("score");scoreState.selected.clear();$("scorePoolSearch").value="";try{await loadPools(true)}catch(error){scoreMessage("scoreSetupError",`Pools were created, but the list could not refresh: ${error.message||error}. Refresh pools to try again.`);return}refreshScorePools(workflowState.pools);for(const name of names||[])scoreChoosePool(name,true);if((names||[]).length>32)scoreMessage("scoreSetupError","The first 32 pools are selected. Score the remaining pools in another run.");$("scoreWorkspace").scrollIntoView({block:"start"})}
$("scorePoolSearch").oninput=renderScorePools;
$("scoreRefreshPools").onclick=async()=>{scoreMessage("scoreSetupError","");try{await loadPools(true);scoreState.descriptionRevision++;scoreState.descriptions.clear();refreshScorePools(workflowState.pools);for(const name of scoreState.selected.keys())scoreDescribePool(name)}catch(error){scoreMessage("scoreSetupError",error)}};
$("scoreSelectVisible").onclick=()=>{for(const pool of scoreFilteredPools())if(!scorePoolUnavailable(pool))scoreChoosePool(pool.name,true)};
$("scoreClearSelection").onclick=()=>{scoreState.selected.clear();renderScorePools();scoreMessage("scoreSetupError","")};
$("scoreStartBtn").onclick=startScoreRun;$("scoreRefreshJobs").onclick=()=>refreshScoreJobs();$("scoreJobSelect").onchange=()=>selectScoreJob($("scoreJobSelect").value);
$("scoreCancelBtn").onclick=()=>changeScoreRun("cancel");$("scoreResumeBtn").onclick=()=>changeScoreRun("resume");$("scoreRetryStatus").onclick=pollScoreJob;
$("scoreResultPool").onchange=()=>{scoreState.resultPool=$("scoreResultPool").value;scoreState.offset=0;scoreState.result=null;renderScoreTable();refreshScoreResults()};$("scoreRefreshResults").onclick=refreshScoreResults;
$("scorePrevPage").onclick=()=>{if(scoreState.offset>0){scoreState.offset=Math.max(0,scoreState.offset-scoreState.pageSize);refreshScoreResults()}};$("scoreNextPage").onclick=()=>{if(scoreState.result&&scoreState.offset+scoreState.pageSize<scoreState.result.total){scoreState.offset+=scoreState.pageSize;refreshScoreResults()}};
for(const id of ["scoreColumnPool","scoreColumnCopy","scoreColumnTags","scoreColumnRoute"])$(id).onchange=renderScoreTable;
'''
